version: "3.9"

services:
  app:
    image: python-flask-tutorial:local-dev
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    stdin_open: true
    tty: true
    # environment:
    #   REDIS_HOST: redis
    command: "python3 -m flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    volumes:
      - .:/app:delegated
    networks:
      - default